[[headers]]
  for = "/assets/css/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/js/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/images/*.{png,jpg,jpeg,gif,svg,webp,ico}"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
